data <- read.csv2("household_power_consumption.txt", na.strings = "?")
colnames(data)
data$Date <- as.Date(data$Date,format= "%d/%m/%Y")
subdata <- subset(data, data$Date=="2007-02-01" | data$Date=="2007-02-02")
subdata$Time <- paste(subdata$Date, subdata$Time)
subdata$Time <- strptime(subdata$Time, format = "%Y-%m-%d %H:%M:%S")
subdata$Sub_metering_1 <- as.numeric(subdata$Sub_metering_1)
subdata$Sub_metering_2 <- as.numeric(subdata$Sub_metering_2)
subdata$Sub_metering_3 <- as.numeric(subdata$Sub_metering_3)
subdata$Global_active_power <- as.numeric(subdata$Global_active_power)
subdata$Global_active_power <- subdata$Global_active_power/1000
subdata$Voltage <- as.numeric(subdata$Voltage)
subdata$Voltage <- subdata$Voltage/10
subdata$Global_reactive_power <- as.numeric(subdata$Global_reactive_power)
subdata$Global_reactive_power <- subdata$Global_reactive_power/1000
png("plot4.png")
par(mfcol = c(2,2), mar = c(4,4,1,1))
plot(subdata$Time, subdata$Global_active_power, ylab = "Global Active Power", xlab="",type = "n")
lines(subdata$Time, subdata$Global_active_power)
plot(subdata$Time, subdata$Sub_metering_1, ylab = "Energy Submetering", xlab="",type = "n")
lines(subdata$Time, subdata$Sub_metering_1, col="black")
lines(subdata$Time, subdata$Sub_metering_2, col="red")
lines(subdata$Time, subdata$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black","red", "blue"), lty = 1, cex=0.75)
plot(subdata$Time, subdata$Voltage, ylab = "Voltage", xlab="datetime",type = "n")
lines(subdata$Time, subdata$Voltage)
plot(subdata$Time, subdata$Global_reactive_power, ylab = "Global_rective_power", xlab="datetime",type = "n")
lines(subdata$Time, subdata$Global_reactive_power)
dev.off()