data <- read.csv2("household_power_consumption.txt", na.strings = "?")
colnames(data)
data$Date <- as.Date(data$Date,format= "%d/%m/%Y")
subdata <- subset(data, data$Date=="2007-02-01" | data$Date=="2007-02-02")
subdata$Time <- paste(subdata$Date, subdata$Time)
subdata$Time <- strptime(subdata$Time, format = "%Y-%m-%d %H:%M:%S")
subdata$Sub_metering_1 <- as.numeric(subdata$Sub_metering_1)
subdata$Sub_metering_2 <- as.numeric(subdata$Sub_metering_2)
subdata$Sub_metering_3 <- as.numeric(subdata$Sub_metering_3)
png("plot3.png")
plot(subdata$Time, subdata$Sub_metering_1, ylab = "Energy Submetering", xlab="",type = "n")
lines(subdata$Time, subdata$Sub_metering_1, col="black")
lines(subdata$Time, subdata$Sub_metering_2, col="red")
lines(subdata$Time, subdata$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black","red", "blue"), lty = 1)
dev.off()